### ISSUE TITLE
Hosted API docs?

### ISSUE THREAD

**Issue by sunng87** [hellonico/origami#33]
Thank you for this awesome library. It would be nice if you provide a API doc in your doc site. [Codox](https://github.com/weavejester/codox) has been a great tool for Clojure doc generation.

Actually the doc of all jars published on clojars are automatically generated on cljdoc.org. However, they seems to have trouble with (origami)[https://cljdoc.org/d/origami] .

**Comment by hellonico** [comment]
Hi !

Great idea.
Had a quick look and the reason is I am not including the mxnet library by default in the dependencies but I do have a namespace depending on it.
When the clojure doc command runs, it spans all the namespaces and requires that mxnet library in the pom file.

Will fix that this week and keep you posted.

**Comment by hellonico** [comment]
Adding build logs here:
https://circleci.com/gh/cljdoc/builder/18314

**Comment by hellonico** [comment]
http://origamidocs.hellonico.info/codox/index.html

**Comment by hellonico** [comment]
Also updated the front page readme. 
https://github.com/hellonico/origami/blob/master/README.md

**Comment by sunng87** [comment]
Thank you!
